name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore DotnetDockerDemo.csproj

      - name: Build project
        run: dotnet build DotnetDockerDemo.csproj --no-restore --configuration Release

      - name: Publish project
        run: dotnet publish DotnetDockerDemo.csproj --no-build --configuration Release -o out

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t yourdockerhubusername/dotnet-docker-demo:latest .

      - name: Push Docker image
        run: docker push yourdockerhubusername/dotnet-docker-demo:latest
